<?php

declare(strict_types=1);

return [
    'title' => 'Pato ao Alvo',
    'version' => '1.5.0',
    'roundDuration' => 60,
    'bows' => [
        1 => [
            'name' => 'Arco de Madeira',
            'arrowName' => 'Flecha de Madeira',
            'effectLabel' => 'Básica',
            'specialEffect' => 'none',
            'specialEffectEnabled' => false,
            'arrowVisual' => 'wood',
            'arrowAccent' => '#7a3d1f',
            'price' => 0,
            'damage' => 1,
            'precision' => 1.00,
            'range' => 1.00,
            'arrowSpeed' => 1.00,
            'shotsPerSecond' => .80,
            'color' => '#b96832',
            'arrowShaft' => '#e8d3a2',
            'arrowTip' => '#d8dde1',
            'spriteFrame' => 1,
            'spriteFilter' => 'none',
            'description' => 'Equipamento inicial, simples e equilibrado.',
        ],
        2 => [
            'name' => 'Arco Reforçado',
            'arrowName' => 'Flecha Reforçada',
            'effectLabel' => 'Mais rápida',
            'specialEffect' => 'none',
            'specialEffectEnabled' => false,
            'arrowVisual' => 'reinforced',
            'arrowAccent' => '#e5f1f6',
            'price' => 150,
            'damage' => 1,
            'precision' => 1.05,
            'range' => 1.08,
            'arrowSpeed' => 1.08,
            'shotsPerSecond' => .90,
            'color' => '#5ba7d8',
            'arrowShaft' => '#c7d7df',
            'arrowTip' => '#aebcc5',
            'spriteFrame' => 2,
            'spriteFilter' => 'saturate(.75)',
            'description' => 'Madeira reforçada e disparos mais rápidos.',
        ],
        3 => [
            'name' => 'Arco de Caçador',
            'arrowName' => 'Flecha de Caçador',
            'effectLabel' => 'Mais precisa',
            'specialEffect' => 'none',
            'specialEffectEnabled' => false,
            'arrowVisual' => 'hunter',
            'arrowAccent' => '#d7f0a4',
            'price' => 400,
            'damage' => 1,
            'precision' => 1.22,
            'range' => 1.12,
            'arrowSpeed' => 1.10,
            'shotsPerSecond' => 1.00,
            'color' => '#4fbf67',
            'arrowShaft' => '#b9d89d',
            'arrowTip' => '#d8e4d0',
            'spriteFrame' => 1,
            'spriteFilter' => 'hue-rotate(62deg) saturate(1.15)',
            'description' => 'Construído para tiros estáveis e precisos.',
        ],
        4 => [
            'name' => 'Arco de Ferro',
            'arrowName' => 'Flecha de Ferro',
            'effectLabel' => 'Mais dano',
            'specialEffect' => 'none',
            'specialEffectEnabled' => false,
            'arrowVisual' => 'iron',
            'arrowAccent' => '#667984',
            'price' => 800,
            'damage' => 2,
            'precision' => 1.28,
            'range' => 1.22,
            'arrowSpeed' => 1.12,
            'shotsPerSecond' => 1.08,
            'color' => '#94a3ad',
            'arrowShaft' => '#aab6bd',
            'arrowTip' => '#eef4f6',
            'spriteFrame' => 2,
            'spriteFilter' => 'grayscale(.8) brightness(.95)',
            'description' => 'Estrutura metálica e impacto mais pesado.',
        ],
        5 => [
            'name' => 'Arco Flamejante',
            'arrowName' => '🔥 Flecha de Fogo',
            'effectLabel' => 'Dano extra · efeito futuro',
            'specialEffect' => 'fire',
            'specialEffectEnabled' => false,
            'arrowVisual' => 'fire',
            'arrowAccent' => '#ffe45c',
            'price' => 1400,
            'damage' => 3,
            'precision' => 1.35,
            'range' => 1.34,
            'arrowSpeed' => 1.14,
            'shotsPerSecond' => 1.18,
            'color' => '#ff6a24',
            'arrowShaft' => '#d95a27',
            'arrowTip' => '#ffd35a',
            'spriteFrame' => 3,
            'spriteFilter' => 'hue-rotate(-18deg) saturate(1.35)',
            'description' => 'Chamas visuais; dano contínuo virá depois.',
        ],
        6 => [
            'name' => 'Arco Congelante',
            'arrowName' => '❄️ Flecha de Gelo',
            'effectLabel' => 'Desaceleração · efeito futuro',
            'specialEffect' => 'freeze',
            'specialEffectEnabled' => false,
            'arrowVisual' => 'ice',
            'arrowAccent' => '#ffffff',
            'price' => 2200,
            'damage' => 3,
            'precision' => 1.42,
            'range' => 1.42,
            'arrowSpeed' => 1.16,
            'shotsPerSecond' => 1.25,
            'color' => '#55d7ff',
            'arrowShaft' => '#a8efff',
            'arrowTip' => '#e9fcff',
            'spriteFrame' => 2,
            'spriteFilter' => 'hue-rotate(155deg) saturate(1.35)',
            'description' => 'Gelo visual; lentidão será adicionada depois.',
        ],
        7 => [
            'name' => 'Arco Elétrico',
            'arrowName' => '⚡ Flecha Elétrica',
            'effectLabel' => 'Acerto em cadeia · efeito futuro',
            'specialEffect' => 'chain',
            'specialEffectEnabled' => false,
            'arrowVisual' => 'electric',
            'arrowAccent' => '#fffbd0',
            'price' => 3200,
            'damage' => 4,
            'precision' => 1.50,
            'range' => 1.52,
            'arrowSpeed' => 1.18,
            'shotsPerSecond' => 1.35,
            'color' => '#ffe23d',
            'arrowShaft' => '#ffe970',
            'arrowTip' => '#fffbd0',
            'spriteFrame' => 3,
            'spriteFilter' => 'hue-rotate(18deg) saturate(1.45)',
            'description' => 'Descarga visual; corrente elétrica virá depois.',
        ],
        8 => [
            'name' => 'Arco de Cristal',
            'arrowName' => '💎 Flecha de Cristal',
            'effectLabel' => 'Alta precisão',
            'specialEffect' => 'crystal',
            'specialEffectEnabled' => false,
            'arrowVisual' => 'crystal',
            'arrowAccent' => '#c8a7ff',
            'price' => 4500,
            'damage' => 4,
            'precision' => 1.75,
            'range' => 1.64,
            'arrowSpeed' => 1.20,
            'shotsPerSecond' => 1.45,
            'color' => '#67f3ea',
            'arrowShaft' => '#a6fff7',
            'arrowTip' => '#e8fffd',
            'spriteFrame' => 4,
            'spriteFilter' => 'hue-rotate(62deg) saturate(1.3)',
            'description' => 'Cristal lapidado para máxima estabilidade.',
        ],
        9 => [
            'name' => 'Arco Lendário',
            'arrowName' => '🌟 Flecha Lendária',
            'effectLabel' => 'Grande alcance e dano',
            'specialEffect' => 'legendary',
            'specialEffectEnabled' => false,
            'arrowVisual' => 'legendary',
            'arrowAccent' => '#ffe36a',
            'price' => 6500,
            'damage' => 5,
            'precision' => 1.90,
            'range' => 1.86,
            'arrowSpeed' => 1.24,
            'shotsPerSecond' => 1.58,
            'color' => '#b84dff',
            'arrowShaft' => '#ebc7ff',
            'arrowTip' => '#ffe36a',
            'spriteFrame' => 4,
            'spriteFilter' => 'none',
            'description' => 'Grande alcance, dano elevado e energia lendária.',
        ],
        10 => [
            'name' => 'Arco Supremo',
            'arrowName' => '👑 Flecha Suprema',
            'effectLabel' => 'Atributos máximos',
            'specialEffect' => 'supreme',
            'specialEffectEnabled' => false,
            'arrowVisual' => 'supreme',
            'arrowAccent' => '#ffffff',
            'price' => 9000,
            'damage' => 6,
            'precision' => 2.10,
            'range' => 2.10,
            'arrowSpeed' => 1.28,
            'shotsPerSecond' => 1.72,
            'color' => '#ffd447',
            'arrowShaft' => '#fff0a2',
            'arrowTip' => '#ffffff',
            'spriteFrame' => 4,
            'spriteFilter' => 'hue-rotate(-38deg) saturate(1.45) brightness(1.08)',
            'description' => 'O equipamento final, com os melhores atributos.',
        ],
    ],
    'ducks' => [
        'common' => [
            'name' => 'Pato Comum', 'points' => 5, 'coins' => 4, 'health' => 2,
            'speedMultiplier' => 1.00, 'movement' => 'wave', 'size' => 1.00,
            'bodyColor' => '#f4f1dc', 'wingColor' => '#c9914c', 'headColor' => '#26a968',
        ],
        'blue' => [
            'name' => 'Pato Azul', 'points' => 8, 'coins' => 6, 'health' => 3,
            'speedMultiplier' => 1.35, 'movement' => 'swift', 'size' => .94,
            'bodyColor' => '#dff5ff', 'wingColor' => '#4ca4e8', 'headColor' => '#2587dc',
        ],
        'red' => [
            'name' => 'Pato Vermelho', 'points' => 12, 'coins' => 8, 'health' => 4,
            'speedMultiplier' => 1.15, 'movement' => 'zigzag', 'size' => 1.00,
            'bodyColor' => '#ffe3d6', 'wingColor' => '#d94a45', 'headColor' => '#e63d42',
        ],
        'purple' => [
            'name' => 'Pato Roxo', 'points' => 18, 'coins' => 12, 'health' => 6,
            'speedMultiplier' => .90, 'movement' => 'heavy', 'size' => 1.08,
            'bodyColor' => '#eee0ff', 'wingColor' => '#8e4bc1', 'headColor' => '#923dcc',
        ],
        'golden' => [
            'name' => 'Pato Dourado', 'points' => 30, 'coins' => 22, 'health' => 8,
            'speedMultiplier' => 1.25, 'movement' => 'swift', 'size' => 1.02,
            'bodyColor' => '#fff0a3', 'wingColor' => '#e9a91b', 'headColor' => '#ffc62e',
        ],
        'king' => [
            'name' => 'Pato Rei', 'points' => 60, 'coins' => 45, 'health' => 12,
            'speedMultiplier' => .75, 'movement' => 'royal', 'size' => 1.24,
            'bodyColor' => '#fff4d2', 'wingColor' => '#d59a31', 'headColor' => '#237f59',
        ],
    ],
];
